### ISSUE TITLE
'--table-name' flag is ignored

### ISSUE THREAD

**Issue by floitsch** [peterldowns/pgmigrate#3]
It looks like the `--table-name` flag is ignored (at least for `apply`).

The `TableName` is set to the `DefaultTableName` but isn't updated: https://github.com/peterldowns/pgmigrate/blob/main/migrator.go#L68

**Comment by peterldowns** [comment]
You are entirely correct — thank you for the bug report, I will fix this.

**Comment by peterldowns** [comment]
Should be fixed now!
